<?php
	$local = __DIR__;
	$domain = 'http://medsallovertheworld.com/';

	function getProductName($link) {
		global $domain;
		$name = str_replace('&amp;', '&', $link);
		$replacement = array(
			$domain,
			'-%lang%.html',
			'%prefix%'
		);
		$name = str_replace($replacement, '', $name);
		$name = str_replace(getPrefix(), '', $name);
		$name = preg_replace('/[^a-zA-Z]+/','-', $name);
		return $name;
	}

	function getContent($link){
		global $all_links;
		$params = array(
			'language' => strtoupper($all_links[$link]['lang']),
		);
		return Sender::curlGetContent($link, 'POST', $params);
		//return file_get_contents($_POST['href']);
	}

	include(__DIR__ . '/../lib/main.php');

	if($_POST) { return; }
?>
<script>
	function parseContent(html){
		var error = $(html).find('section.product').length ? 0 : 1;

		var img = $(html).find('.list-unstyled img').first();
		var image = $(img).attr('src');
		var image_info = '';
		if(img.attr('alt')){
			image_info += "\n" + 'alt: "' + $(img).attr('alt') + '"';
		}
		if(img.attr('title')){
			image_info += "\n" + 'title: "' + $(img).attr('title') + '"';
		}

		var title = $(html).find('header h1').first();
		$(title).find('span').remove();
		title = $(title).text();

		var short_description = $(html).find('section.product .short-descr, section.product .text').text();

		var full_description = $(html).find('.simple-article').text();

		var data = {
			error: error,
			parse: href,
			href: href,
			image: image,
			image_info: image_info,
			title: title,
			short_description: short_description,
			full_description: full_description,
		}

		return data;
	}
</script>
<?php
	function getPrefix(){
		return array(
			'us' => 'buy-',
			'es' => 'comprar-',
			'mx' => 'comprar-',
			'br' => 'comprar-',
			'uk' => 'buy-',
			'eu' => 'buy-',
			'de' => '',
			'it' => 'compra-',
			'fr' => 'acheter-',
			'pt' => 'comprar-',
			'ca' => 'acheter-',
			'au' => 'buy-',
			'ar' => 'buy-',
			'nz' => 'buy-',
			'be' => 'buy-',
			'dk' => 'buy-',
			'fi' => 'buy-',
			'nl' => 'buy-',
			'no' => 'buy-',
			'se' => 'buy-',
			'tr' => 'buy-',
			'jp' => 'buy-',
			'gr' => 'buy-',
			'hu' => 'buy-',
			'cz' => 'buy-',
			'pl' => 'buy-',
		);
	}

	function getLangs(){
		return array(
			'us' => 'usa',
			'es' => 'spain',
			'mx' => 'mexico',
			'br' => 'brazil',
			'uk' => 'uk',
			'eu' => 'europe',
			'de' => 'kaufen',
			'it' => 'italy',
			'fr' => 'france',
			'pt' => 'portugal',
			'ca' => 'canada',
			'au' => 'au',
			'ar' => 'ar',
			'nz' => 'nz',
			'be' => 'be',
			'dk' => 'dk',
			'fi' => 'fi',
			'nl' => 'nl',
			'no' => 'no',
			'se' => 'se',
			'tr' => 'tr',
			'jp' => 'jp',
			'gr' => 'gr',
			'hu' => 'hu',
			'cz' => 'cz',
			'pl' => 'pl',
		);
	}

	function getLinks(){
		return array(
			$domain . '%prefix%antabuse-%lang%.html',
			$domain . '%prefix%revia-%lang%.html',
			$domain . '%prefix%aricept-%lang%.html',
			$domain . '%prefix%artane-%lang%.html',
			$domain . '%prefix%azilect-%lang%.html',
			$domain . '%prefix%dostinex-%lang%.html',
			$domain . '%prefix%eldepryl-%lang%.html',
			$domain . '%prefix%exelon-%lang%.html',
			$domain . '%prefix%kemadrin-%lang%.html',
			$domain . '%prefix%mirapex-%lang%.html',
			$domain . '%prefix%namenda-%lang%.html',
			$domain . '%prefix%namzaric-%lang%.html',
			$domain . '%prefix%parlodel-%lang%.html',
			$domain . '%prefix%reminyl-%lang%.html',
			$domain . '%prefix%requip-%lang%.html',
			$domain . '%prefix%sinemet-%lang%.html',
			$domain . '%prefix%sinemet-cr-%lang%.html',
			$domain . '%prefix%stalevo-%lang%.html',
			$domain . '%prefix%symmetrel-%lang%.html',
			$domain . '%prefix%arcoxia-%lang%.html',
			$domain . '%prefix%cymbalta-%lang%.html',
			$domain . '%prefix%feldene-%lang%.html',
			$domain . '%prefix%indocin-%lang%.html',
			$domain . '%prefix%indocin-sr-%lang%.html',
			$domain . '%prefix%lyrica-%lang%.html',
			$domain . '%prefix%motrin-%lang%.html',
			$domain . '%prefix%naprosyn-%lang%.html',
			$domain . '%prefix%neurontin-%lang%.html',
			$domain . '%prefix%nimotop-%lang%.html',
			$domain . '%prefix%ponstel-%lang%.html',
			$domain . '%prefix%pyridium-%lang%.html',
			$domain . '%prefix%tegretol-%lang%.html',
			$domain . '%prefix%tylenol-%lang%.html',
			$domain . '%prefix%voltaren-%lang%.html',
			$domain . '%prefix%xylocaine-%lang%.html',
			$domain . '%prefix%arava-%lang%.html',
			$domain . '%prefix%aristocort-%lang%.html',
			$domain . '%prefix%asacol-%lang%.html',
			$domain . '%prefix%azulfidine-%lang%.html',
			$domain . '%prefix%canasa-%lang%.html',
			$domain . '%prefix%celebrex-%lang%.html',
			$domain . '%prefix%colcrys-%lang%.html',
			$domain . '%prefix%cortaid-%lang%.html',
			$domain . '%prefix%deltasone-%lang%.html',
			$domain . '%prefix%dexone-%lang%.html',
			$domain . '%prefix%diprolene-%lang%.html',
			$domain . '%prefix%emflaza-%lang%.html',
			$domain . '%prefix%estrace-%lang%.html',
			$domain . '%prefix%fusiderm-b-%lang%.html',
			$domain . '%prefix%ilosone-%lang%.html',
			$domain . '%prefix%lotemax-%lang%.html',
			$domain . '%prefix%medrol-active-%lang%.html',
			$domain . '%prefix%mobic-%lang%.html',
			$domain . '%prefix%pentasa-%lang%.html',
			$domain . '%prefix%symbicort-%lang%.html',
			$domain . '%prefix%synalar-%lang%.html',
			$domain . '%prefix%temovate-%lang%.html',
			$domain . '%prefix%voltaren-gel-%lang%.html',
			$domain . '%prefix%acular-%lang%.html',
			$domain . '%prefix%geriforte-syrup-%lang%.html',
			$domain . '%prefix%locoid-%lang%.html',
			$domain . '%prefix%lodine-%lang%.html',
			$domain . '%prefix%allegra-%lang%.html',
			$domain . '%prefix%atarax-%lang%.html',
			$domain . '%prefix%bepreve-%lang%.html',
			$domain . '%prefix%clarinex-%lang%.html',
			$domain . '%prefix%claritin-%lang%.html',
			$domain . '%prefix%danocrine-%lang%.html',
			$domain . '%prefix%elocon-%lang%.html',
			$domain . '%prefix%optivar-%lang%.html',
			$domain . '%prefix%patanol-%lang%.html',
			$domain . '%prefix%periactin-%lang%.html',
			$domain . '%prefix%rhinocort-%lang%.html',
			$domain . '%prefix%robitussin-%lang%.html',
			$domain . '%prefix%singulair-%lang%.html',
			$domain . '%prefix%xyzal-%lang%.html',
			$domain . '%prefix%zyrtec-%lang%.html',
			$domain . '%prefix%flonase-%lang%.html',
			$domain . '%prefix%amoxil-%lang%.html',
			$domain . '%prefix%augmentin-%lang%.html',
			$domain . '%prefix%avelox-%lang%.html',
			$domain . '%prefix%bactrim-%lang%.html',
			$domain . '%prefix%biaxin-%lang%.html',
			$domain . '%prefix%ceclor-%lang%.html',
			$domain . '%prefix%ceclor-cd-%lang%.html',
			$domain . '%prefix%ceftin-%lang%.html',
			$domain . '%prefix%cefzil-%lang%.html',
			$domain . '%prefix%chloromycetin-%lang%.html',
			$domain . '%prefix%ciloxan-%lang%.html',
			$domain . '%prefix%cipro-%lang%.html',
			$domain . '%prefix%cleocin-%lang%.html',
			$domain . '%prefix%duricef-%lang%.html',
			$domain . '%prefix%flagyl-%lang%.html',
			$domain . '%prefix%floxin-%lang%.html',
			$domain . '%prefix%furadantin-%lang%.html',
			$domain . '%prefix%furacin-%lang%.html',
			$domain . '%prefix%keflex-%lang%.html',
			$domain . '%prefix%levaquin-%lang%.html',
			$domain . '%prefix%lincocin-%lang%.html',
			$domain . '%prefix%minocin-%lang%.html',
			$domain . '%prefix%neggram-%lang%.html',
			$domain . '%prefix%noroxin-%lang%.html',
			$domain . '%prefix%ocuflox-%lang%.html',
			$domain . '%prefix%omnicef-%lang%.html',
			$domain . '%prefix%principen-%lang%.html',
			$domain . '%prefix%rulide-%lang%.html',
			$domain . '%prefix%seromycin-%lang%.html',
			$domain . '%prefix%sumycin-%lang%.html',
			$domain . '%prefix%suprax-%lang%.html',
			$domain . '%prefix%trecator_sc-%lang%.html',
			$domain . '%prefix%vantin-%lang%.html',
			$domain . '%prefix%vibramycin-%lang%.html',
			$domain . '%prefix%xifaxan-%lang%.html',
			$domain . '%prefix%zithromax-%lang%.html',
			$domain . '%prefix%zithromax-dispersible-%lang%.html',
			$domain . '%prefix%zyvox-%lang%.html',
			$domain . '%prefix%fasigyn-%lang%.html',
			$domain . '%prefix%depakote-%lang%.html',
			$domain . '%prefix%dilantin-%lang%.html',
			$domain . '%prefix%keppra-%lang%.html',
			$domain . '%prefix%lamictal-%lang%.html',
			$domain . '%prefix%lamictal-dispersible-%lang%.html',
			$domain . '%prefix%mysoline-%lang%.html',
			$domain . '%prefix%topamax-%lang%.html',
			$domain . '%prefix%trileptal-%lang%.html',
			$domain . '%prefix%videx-ec-%lang%.html',
			$domain . '%prefix%anafranil-%lang%.html',
			$domain . '%prefix%aventyl-%lang%.html',
			$domain . '%prefix%aygestin-%lang%.html',
			$domain . '%prefix%celexa-%lang%.html',
			$domain . '%prefix%desyrel-%lang%.html',
			$domain . '%prefix%effexor-%lang%.html',
			$domain . '%prefix%effexor-xr-%lang%.html',
			$domain . '%prefix%elavil-%lang%.html',
			$domain . '%prefix%fluoxetine-%lang%.html',
			$domain . '%prefix%lexapro-%lang%.html',
			$domain . '%prefix%luvox-%lang%.html',
			$domain . '%prefix%pamelor-%lang%.html',
			$domain . '%prefix%paxil-%lang%.html',
			$domain . '%prefix%paxil-cr-%lang%.html',
			$domain . '%prefix%pristiq-%lang%.html',
			$domain . '%prefix%remeron-%lang%.html',
			$domain . '%prefix%savella-%lang%.html',
			$domain . '%prefix%sinequan-%lang%.html',
			$domain . '%prefix%tofranil-%lang%.html',
			$domain . '%prefix%wellbutrin-sr-%lang%.html',
			$domain . '%prefix%zoloft-%lang%.html',
			$domain . '%prefix%betadine-%lang%.html',
			$domain . '%prefix%diflucan-%lang%.html',
			$domain . '%prefix%grifulvin-%lang%.html',
			$domain . '%prefix%gyne_lotrimin-%lang%.html',
			$domain . '%prefix%ketzi-shampoo-%lang%.html',
			$domain . '%prefix%lamisil-%lang%.html',
			$domain . '%prefix%lamisil-cream-%lang%.html',
			$domain . '%prefix%lomexin-%lang%.html',
			$domain . '%prefix%mentax-%lang%.html',
			$domain . '%prefix%nizoral-%lang%.html',
			$domain . '%prefix%nizoral-cream-%lang%.html',
			$domain . '%prefix%nizoral-shampoo-%lang%.html',
			$domain . '%prefix%sporanox-%lang%.html',
			$domain . '%prefix%lotrisone-%lang%.html',
			$domain . '%prefix%acticin-%lang%.html',
			$domain . '%prefix%albenza-%lang%.html',
			$domain . '%prefix%aralen-%lang%.html',
			$domain . '%prefix%plaquenil-%lang%.html',
			$domain . '%prefix%stromectol-%lang%.html',
			$domain . '%prefix%vermox-%lang%.html',
			$domain . '%prefix%banana-condoms-%lang%.html',
			$domain . '%prefix%black-grapes-condoms-%lang%.html',
			$domain . '%prefix%butterscotch-condoms-%lang%.html',
			$domain . '%prefix%chocolate-condoms-%lang%.html',
			$domain . '%prefix%coffee-condoms-%lang%.html',
			$domain . '%prefix%daklinza-%lang%.html',
			$domain . '%prefix%famvir-%lang%.html',
			$domain . '%prefix%green-apple-condoms-%lang%.html',
			$domain . '%prefix%jasmine-condoms-%lang%.html',
			$domain . '%prefix%lamprene-%lang%.html',
			$domain . '%prefix%pineapple-condoms-%lang%.html',
			$domain . '%prefix%pink-condoms-%lang%.html',
			$domain . '%prefix%rebetol-%lang%.html',
			$domain . '%prefix%strawberry-condoms-%lang%.html',
			$domain . '%prefix%valtrex-%lang%.html',
			$domain . '%prefix%zovirax-%lang%.html',
			$domain . '%prefix%tenofovir-emtricitabine-%lang%.html',
			$domain . '%prefix%tenofovir-disoproxil-fumarate-%lang%.html',
			$domain . '%prefix%efavirenz-emtricitabine-tenofovir-%lang%.html',
			$domain . '%prefix%imuran-%lang%.html',
			$domain . '%prefix%neoral-%lang%.html',
			$domain . '%prefix%probalan-%lang%.html',
			$domain . '%prefix%rheumatrex-%lang%.html',
			$domain . '%prefix%advair-diskus-%lang%.html',
			$domain . '%prefix%advair-rotahaler-%lang%.html',
			$domain . '%prefix%serevent-%lang%.html',
			$domain . '%prefix%ventolin-%lang%.html',
			$domain . '%prefix%ventolin-inhaler-%lang%.html',
			$domain . '%prefix%volmax-cr-%lang%.html',
			$domain . '%prefix%vaniqa-%lang%.html',
			$domain . '%prefix%ayurslim-%lang%.html',
			$domain . '%prefix%manjishtha-%lang%.html',
			$domain . '%prefix%viproslim-%lang%.html',
			$domain . '%prefix%grafix-capsules-%lang%.html',
			$domain . '%prefix%grafix-cream-%lang%.html',
			$domain . '%prefix%alesse-%lang%.html',
			$domain . '%prefix%desogen-%lang%.html',
			$domain . '%prefix%diane_35-%lang%.html',
			$domain . '%prefix%yasmin-%lang%.html',
			$domain . '%prefix%apcalis-oral-jelly-%lang%.html',
			$domain . '%prefix%caverta-%lang%.html',
			$domain . '%prefix%eriacta-%lang%.html',
			$domain . '%prefix%intagra-%lang%.html',
			$domain . '%prefix%kamagra-%lang%.html',
			$domain . '%prefix%kamagra-oral-jelly-%lang%.html',
			$domain . '%prefix%kamagra-soft-%lang%.html',
			$domain . '%prefix%pill-organizer-%lang%.html',
			$domain . '%prefix%pill-splitter-%lang%.html',
			$domain . '%prefix%reeflec-v-%lang%.html',
			$domain . '%prefix%silagra-%lang%.html',
			$domain . '%prefix%suhagra-%lang%.html',
			$domain . '%prefix%tadacip-%lang%.html',
			$domain . '%prefix%tadalis-sx-%lang%.html',
			$domain . '%prefix%vigora-%lang%.html',
			$domain . '%prefix%hard-on-%lang%.html',
			$domain . '%prefix%hard-on-oral-jelly-%lang%.html',
			$domain . '%prefix%kamagra-effervescent-%lang%.html',
			$domain . '%prefix%champix-%lang%.html',
			$domain . '%prefix%brand-cialis-%lang%.html',
			$domain . '%prefix%brand-viagra-%lang%.html',
			$domain . '%prefix%brand-levitra-%lang%.html',
			$domain . '%prefix%forzest-%lang%.html',
			$domain . '%prefix%penegra-%lang%.html',
			$domain . '%prefix%arimidex-%lang%.html',
			$domain . '%prefix%aromasin-%lang%.html',
			$domain . '%prefix%casodex-%lang%.html',
			$domain . '%prefix%cytoxan-%lang%.html',
			$domain . '%prefix%droxia-%lang%.html',
			$domain . '%prefix%eulexin-%lang%.html',
			$domain . '%prefix%evista-%lang%.html',
			$domain . '%prefix%gleevec-%lang%.html',
			$domain . '%prefix%iressa-%lang%.html',
			$domain . '%prefix%femara-%lang%.html',
			$domain . '%prefix%nexavar-%lang%.html',
			$domain . '%prefix%nolvadex-%lang%.html',
			$domain . '%prefix%premarin-%lang%.html',
			$domain . '%prefix%revlimid-%lang%.html',
			$domain . '%prefix%synthroid-%lang%.html',
			$domain . '%prefix%tarceva-%lang%.html',
			$domain . '%prefix%vepesid-%lang%.html',
			$domain . '%prefix%xeloda-%lang%.html',
			$domain . '%prefix%aceon-%lang%.html',
			$domain . '%prefix%aczone-%lang%.html',
			$domain . '%prefix%adalat-%lang%.html',
			$domain . '%prefix%adalat-cc-%lang%.html',
			$domain . '%prefix%aggrenox-%lang%.html',
			$domain . '%prefix%altace-%lang%.html',
			$domain . '%prefix%azor-%lang%.html',
			$domain . '%prefix%betapace-%lang%.html',
			$domain . '%prefix%bystolic-%lang%.html',
			$domain . '%prefix%calan-%lang%.html',
			$domain . '%prefix%calan-sr-%lang%.html',
			$domain . '%prefix%cartia-%lang%.html',
			$domain . '%prefix%cartia-xt-%lang%.html',
			$domain . '%prefix%catapres-%lang%.html',
			$domain . '%prefix%cordarone-%lang%.html',
			$domain . '%prefix%coreg-%lang%.html',
			$domain . '%prefix%coumadin-%lang%.html',
			$domain . '%prefix%diovan-%lang%.html',
			$domain . '%prefix%entresto-%lang%.html',
			$domain . '%prefix%imdur-%lang%.html',
			$domain . '%prefix%inderal-%lang%.html',
			$domain . '%prefix%inderal-la-%lang%.html',
			$domain . '%prefix%inspra-%lang%.html',
			$domain . '%prefix%isordil-%lang%.html',
			$domain . '%prefix%isordil-sublingual-%lang%.html',
			$domain . '%prefix%lanoxin-%lang%.html',
			$domain . '%prefix%livalo-%lang%.html',
			$domain . '%prefix%lopressor-%lang%.html',
			$domain . '%prefix%nitrostat-%lang%.html',
			$domain . '%prefix%norvasc-%lang%.html',
			$domain . '%prefix%persantine-%lang%.html',
			$domain . '%prefix%plavix-%lang%.html',
			$domain . '%prefix%pletal-%lang%.html',
			$domain . '%prefix%pradaxa-%lang%.html',
			$domain . '%prefix%procoralan-%lang%.html',
			$domain . '%prefix%rythmol-%lang%.html',
			$domain . '%prefix%edarbi-%lang%.html',
			$domain . '%prefix%tambocor-%lang%.html',
			$domain . '%prefix%tenormin-%lang%.html',
			$domain . '%prefix%ticlid-%lang%.html',
			$domain . '%prefix%tribenzor-%lang%.html',
			$domain . '%prefix%vasotec-%lang%.html',
			$domain . '%prefix%xarelto-%lang%.html',
			$domain . '%prefix%zestril-%lang%.html',
			$domain . '%prefix%ranolazine-%lang%.html',
			$domain . '%prefix%crestor-%lang%.html',
			$domain . '%prefix%lipitor-%lang%.html',
			$domain . '%prefix%lopid-%lang%.html',
			$domain . '%prefix%questran-%lang%.html',
			$domain . '%prefix%tricor-%lang%.html',
			$domain . '%prefix%vytorin-%lang%.html',
			$domain . '%prefix%zetia-%lang%.html',
			$domain . '%prefix%zocor-%lang%.html',
			$domain . '%prefix%actos-%lang%.html',
			$domain . '%prefix%amaryl-%lang%.html',
			$domain . '%prefix%cozaar-%lang%.html',
			$domain . '%prefix%ddavp-%lang%.html',
			$domain . '%prefix%glucophage-%lang%.html',
			$domain . '%prefix%glucophage-xr-%lang%.html',
			$domain . '%prefix%glucotrol-%lang%.html',
			$domain . '%prefix%glucotrol-xl-%lang%.html',
			$domain . '%prefix%glucovance-%lang%.html',
			$domain . '%prefix%janumet-%lang%.html',
			$domain . '%prefix%januvia-%lang%.html',
			$domain . '%prefix%jardiance-%lang%.html',
			$domain . '%prefix%metaglip-%lang%.html',
			$domain . '%prefix%micronase-%lang%.html',
			$domain . '%prefix%onglyza-%lang%.html',
			$domain . '%prefix%prandin-%lang%.html',
			$domain . '%prefix%precose-%lang%.html',
			$domain . '%prefix%starlix-%lang%.html',
			$domain . '%prefix%aldactone-%lang%.html',
			$domain . '%prefix%demadex-%lang%.html',
			$domain . '%prefix%diamox-%lang%.html',
			$domain . '%prefix%lasix-%lang%.html',
			$domain . '%prefix%lozol-%lang%.html',
			$domain . '%prefix%lozol-sr-%lang%.html',
			$domain . '%prefix%moduretic-%lang%.html',
			$domain . '%prefix%frumil-%lang%.html',
			$domain . '%prefix%active-pack-%lang%.html',
			$domain . '%prefix%cialis-%lang%.html',
			$domain . '%prefix%cialis-soft-%lang%.html',
			$domain . '%prefix%cialis-super-active-%lang%.html',
			$domain . '%prefix%cialis-super-force-%lang%.html',
			$domain . '%prefix%cialis-oral-jelly-%lang%.html',
			$domain . '%prefix%classic-pack-%lang%.html',
			$domain . '%prefix%family-pack-%lang%.html',
			$domain . '%prefix%kamagra-gold-%lang%.html',
			$domain . '%prefix%kamagra-polo-%lang%.html',
			$domain . '%prefix%levitra-%lang%.html',
			$domain . '%prefix%light-pack-%lang%.html',
			$domain . '%prefix%female-viagra-%lang%.html',
			$domain . '%prefix%female-cialis-%lang%.html',
			$domain . '%prefix%monster-pack-%lang%.html',
			$domain . '%prefix%professional-pack-%lang%.html',
			$domain . '%prefix%soft-pack-%lang%.html',
			$domain . '%prefix%suhagra-force-%lang%.html',
			$domain . '%prefix%strong-pack-%lang%.html',
			$domain . '%prefix%super-p-force-jelly-%lang%.html',
			$domain . '%prefix%super-p-force-%lang%.html',
			$domain . '%prefix%triple-trial-pack-%lang%.html',
			$domain . '%prefix%viagra-%lang%.html',
			$domain . '%prefix%viagra-soft-%lang%.html',
			$domain . '%prefix%viagra-super-active-%lang%.html',
			$domain . '%prefix%zenegra-%lang%.html',
			$domain . '%prefix%zydena-%lang%.html',
			$domain . '%prefix%cialis-daily-%lang%.html',
			$domain . '%prefix%cialis-strips-%lang%.html',
			$domain . '%prefix%cialis-pack-%lang%.html',
			$domain . '%prefix%cialis-professional-%lang%.html',
			$domain . '%prefix%cialis-sublingual-%lang%.html',
			$domain . '%prefix%cialis-black-%lang%.html',
			$domain . '%prefix%viagra-pack-%lang%.html',
			$domain . '%prefix%viagra-professional-%lang%.html',
			$domain . '%prefix%viagra-sublingual-%lang%.html',
			$domain . '%prefix%viagra-super-dulox_force-%lang%.html',
			$domain . '%prefix%viagra-super-fluox_force-%lang%.html',
			$domain . '%prefix%viagra-super-force-%lang%.html',
			$domain . '%prefix%viagra-strips-%lang%.html',
			$domain . '%prefix%levitra-soft-%lang%.html',
			$domain . '%prefix%levitra-super-force-%lang%.html',
			$domain . '%prefix%levitra-professional-%lang%.html',
			$domain . '%prefix%avana-%lang%.html',
			$domain . '%prefix%super-avana-%lang%.html',
			$domain . '%prefix%top-avana-%lang%.html',
			$domain . '%prefix%extra-super-avana-%lang%.html',
			$domain . '%prefix%extra-super-p-force-%lang%.html',
			$domain . '%prefix%yagara-%lang%.html',
			$domain . '%prefix%sildalis-%lang%.html',
			$domain . '%prefix%silvitra-%lang%.html',
			$domain . '%prefix%viagra-oral-jelly-%lang%.html',
			$domain . '%prefix%tadora-%lang%.html',
			$domain . '%prefix%alphagan-%lang%.html',
			$domain . '%prefix%azopt-%lang%.html',
			$domain . '%prefix%betagan-%lang%.html',
			$domain . '%prefix%bimatoprost-%lang%.html',
			$domain . '%prefix%cosopt-%lang%.html',
			$domain . '%prefix%cyclogyl-%lang%.html',
			$domain . '%prefix%timoptic-%lang%.html',
			$domain . '%prefix%trusopt-%lang%.html',
			$domain . '%prefix%xalatan-%lang%.html',
			$domain . '%prefix%aciphex-%lang%.html',
			$domain . '%prefix%acofide-%lang%.html',
			$domain . '%prefix%buscopan-%lang%.html',
			$domain . '%prefix%colofac-%lang%.html',
			$domain . '%prefix%creon-%lang%.html',
			$domain . '%prefix%cytotec-%lang%.html',
			$domain . '%prefix%dulcolax-%lang%.html',
			$domain . '%prefix%imodium-%lang%.html',
			$domain . '%prefix%motilium-%lang%.html',
			$domain . '%prefix%nexium-%lang%.html',
			$domain . '%prefix%ovol-%lang%.html',
			$domain . '%prefix%pepcid-%lang%.html',
			$domain . '%prefix%prevacid-%lang%.html',
			$domain . '%prefix%prilosec-%lang%.html',
			$domain . '%prefix%protonix-%lang%.html',
			$domain . '%prefix%reglan-%lang%.html',
			$domain . '%prefix%valproate-%lang%.html',
			$domain . '%prefix%zantac-%lang%.html',
			$domain . '%prefix%zofran-%lang%.html',
			$domain . '%prefix%dramamine-%lang%.html',
			$domain . '%prefix%antivert-%lang%.html',
			$domain . '%prefix%abana-%lang%.html',
			$domain . '%prefix%jesibi-%lang%.html',
			$domain . '%prefix%jesibi-cream-%lang%.html',
			$domain . '%prefix%naron-%lang%.html',
			$domain . '%prefix%penon-%lang%.html',
			$domain . '%prefix%vpxl-%lang%.html',
			$domain . '%prefix%amalaki-%lang%.html',
			$domain . '%prefix%arjuna-%lang%.html',
			$domain . '%prefix%ashvagandha-%lang%.html',
			$domain . '%prefix%bael-%lang%.html',
			$domain . '%prefix%brahmi-%lang%.html',
			$domain . '%prefix%confido-%lang%.html',
			$domain . '%prefix%diabecon-%lang%.html',
			$domain . '%prefix%diakof-%lang%.html',
			$domain . '%prefix%excel-capsules-%lang%.html',
			$domain . '%prefix%v-excel-%lang%.html',
			$domain . '%prefix%geriforte-%lang%.html',
			$domain . '%prefix%gokshura-%lang%.html',
			$domain . '%prefix%guduchi-%lang%.html',
			$domain . '%prefix%haridra-%lang%.html',
			$domain . '%prefix%himcolin-gel-%lang%.html',
			$domain . '%prefix%kapikachhu-%lang%.html',
			$domain . '%prefix%karela-%lang%.html',
			$domain . '%prefix%lasuna-%lang%.html',
			$domain . '%prefix%mandukaparni-%lang%.html',
			$domain . '%prefix%meshashringi-%lang%.html',
			$domain . '%prefix%penisole-%lang%.html',
			$domain . '%prefix%neem-%lang%.html',
			$domain . '%prefix%punarnava-%lang%.html',
			$domain . '%prefix%reosto-%lang%.html',
			$domain . '%prefix%rumalaya-liniment-%lang%.html',
			$domain . '%prefix%shallaki-%lang%.html',
			$domain . '%prefix%shatavari-%lang%.html',
			$domain . '%prefix%shigru-%lang%.html',
			$domain . '%prefix%shuddha-guggulu-%lang%.html',
			$domain . '%prefix%wondersleep-%lang%.html',
			$domain . '%prefix%tagara-%lang%.html',
			$domain . '%prefix%triphala-%lang%.html',
			$domain . '%prefix%tulasi-%lang%.html',
			$domain . '%prefix%vasaka-%lang%.html',
			$domain . '%prefix%yashtimadhu-%lang%.html',
			$domain . '%prefix%vigrx-%lang%.html',
			$domain . '%prefix%liv.52-%lang%.html',
			$domain . '%prefix%combivir-%lang%.html',
			$domain . '%prefix%crixivan-%lang%.html',
			$domain . '%prefix%epivir-%lang%.html',
			$domain . '%prefix%hiv_1_2-test-%lang%.html',
			$domain . '%prefix%kaletra-%lang%.html',
			$domain . '%prefix%norvir-%lang%.html',
			$domain . '%prefix%retrovir-%lang%.html',
			$domain . '%prefix%efavirenz-%lang%.html',
			$domain . '%prefix%syphilis-test-%lang%.html',
			$domain . '%prefix%ziagen-%lang%.html',
			$domain . '%prefix%adcirca-%lang%.html',
			$domain . '%prefix%avalide-%lang%.html',
			$domain . '%prefix%avapro-%lang%.html',
			$domain . '%prefix%benicar-%lang%.html',
			$domain . '%prefix%benicar-hct-%lang%.html',
			$domain . '%prefix%cardura-%lang%.html',
			$domain . '%prefix%diovan-hct-%lang%.html',
			$domain . '%prefix%hytrin-%lang%.html',
			$domain . '%prefix%hyzaar-%lang%.html',
			$domain . '%prefix%micardis-%lang%.html',
			$domain . '%prefix%micardis-hct-%lang%.html',
			$domain . '%prefix%microzide-%lang%.html',
			$domain . '%prefix%minipress-%lang%.html',
			$domain . '%prefix%plendil-%lang%.html',
			$domain . '%prefix%revatio-%lang%.html',
			$domain . '%prefix%tenoretic-%lang%.html',
			$domain . '%prefix%trandate-%lang%.html',
			$domain . '%prefix%vaseretic-%lang%.html',
			$domain . '%prefix%zebeta-%lang%.html',
			$domain . '%prefix%zestoretic-%lang%.html',
			$domain . '%prefix%ziac-%lang%.html',
			$domain . '%prefix%avodart-%lang%.html',
			$domain . '%prefix%emla-%lang%.html',
			$domain . '%prefix%flomax-%lang%.html',
			$domain . '%prefix%jalyn-%lang%.html',
			$domain . '%prefix%priligy-%lang%.html',
			$domain . '%prefix%propecia-%lang%.html',
			$domain . '%prefix%proscar-%lang%.html',
			$domain . '%prefix%rogaine-%lang%.html',
			$domain . '%prefix%suhagra-duralong-%lang%.html',
			$domain . '%prefix%testosterone-%lang%.html',
			$domain . '%prefix%uroxatral-%lang%.html',
			$domain . '%prefix%abilify-%lang%.html',
			$domain . '%prefix%anafranil-sr-%lang%.html',
			$domain . '%prefix%buspar-%lang%.html',
			$domain . '%prefix%clozaril-%lang%.html',
			$domain . '%prefix%compazine-%lang%.html',
			$domain . '%prefix%geodon-%lang%.html',
			$domain . '%prefix%lithobid-%lang%.html',
			$domain . '%prefix%loxitane-%lang%.html',
			$domain . '%prefix%mellaril-%lang%.html',
			$domain . '%prefix%risperdal-%lang%.html',
			$domain . '%prefix%seroquel-%lang%.html',
			$domain . '%prefix%strattera-%lang%.html',
			$domain . '%prefix%thorazine-%lang%.html',
			$domain . '%prefix%zyprexa-%lang%.html',
			$domain . '%prefix%nootropil-%lang%.html',
			$domain . '%prefix%imitrex-%lang%.html',
			$domain . '%prefix%maxalt-%lang%.html',
			$domain . '%prefix%relpax-%lang%.html',
			$domain . '%prefix%zomig-%lang%.html',
			$domain . '%prefix%flexeril-%lang%.html',
			$domain . '%prefix%lioresal-%lang%.html',
			$domain . '%prefix%parafon-%lang%.html',
			$domain . '%prefix%robaxin-%lang%.html',
			$domain . '%prefix%skelaxin-%lang%.html',
			$domain . '%prefix%zanaflex-%lang%.html',
			$domain . '%prefix%mestinon-%lang%.html',
			$domain . '%prefix%xenical-%lang%.html',
			$domain . '%prefix%actonel-%lang%.html',
			$domain . '%prefix%boniva-%lang%.html',
			$domain . '%prefix%fosamax-%lang%.html',
			$domain . '%prefix%myambutol-%lang%.html',
			$domain . '%prefix%rifadin-%lang%.html',
			$domain . '%prefix%spiriva-%lang%.html',
			$domain . '%prefix%tessalon-%lang%.html',
			$domain . '%prefix%combivent-%lang%.html',
			$domain . '%prefix%aldara-%lang%.html',
			$domain . '%prefix%azelex-%lang%.html',
			$domain . '%prefix%bactroban-%lang%.html',
			$domain . '%prefix%benzoyl-%lang%.html',
			$domain . '%prefix%contractubex-%lang%.html',
			$domain . '%prefix%brand-contractubex-%lang%.html',
			$domain . '%prefix%desonate-%lang%.html',
			$domain . '%prefix%differin-%lang%.html',
			$domain . '%prefix%efudex-%lang%.html',
			$domain . '%prefix%oxsoralen-%lang%.html',
			$domain . '%prefix%renova-%lang%.html',
			$domain . '%prefix%salicylic-acid-%lang%.html',
			$domain . '%prefix%scanil-%lang%.html',
			$domain . '%prefix%scarend-silicone-%lang%.html',
			$domain . '%prefix%shield-%lang%.html',
			$domain . '%prefix%ziana-%lang%.html',
			$domain . '%prefix%cellcept-%lang%.html',
			$domain . '%prefix%cyklokapron-%lang%.html',
			$domain . '%prefix%prograf-%lang%.html',
			$domain . '%prefix%protopic-%lang%.html',
			$domain . '%prefix%urecholine-%lang%.html',
			$domain . '%prefix%actigall-%lang%.html',
			$domain . '%prefix%cycrin-%lang%.html',
			$domain . '%prefix%detrol-%lang%.html',
			$domain . '%prefix%detrol-la-%lang%.html',
			$domain . '%prefix%enablex-%lang%.html',
			$domain . '%prefix%norlutate-%lang%.html',
			$domain . '%prefix%oxytrol-%lang%.html',
			$domain . '%prefix%phoslo-%lang%.html',
			$domain . '%prefix%renagel-%lang%.html',
			$domain . '%prefix%rocaltrol-%lang%.html',
			$domain . '%prefix%urispas-%lang%.html',
			$domain . '%prefix%vesicare-%lang%.html',
			$domain . '%prefix%zyloprim-%lang%.html',
			$domain . '%prefix%vitamin-b12-%lang%.html',
			$domain . '%prefix%vitamin-c-%lang%.html',
			$domain . '%prefix%addyi-%lang%.html',
			$domain . '%prefix%clomid-%lang%.html',
			$domain . '%prefix%diclegis-%lang%.html',
			$domain . '%prefix%duphaston-%lang%.html',
			$domain . '%prefix%ovulation-test-%lang%.html',
			$domain . '%prefix%pregnancy-test-card-%lang%.html',
			$domain . '%prefix%pregnancy-test-strip-%lang%.html',
			$domain . '%prefix%prometrium-%lang%.html',
		);
	}
?>